version: "3"
services:
    postgres:
        container_name: postgres
        volumes:
            - /home/raspi/nextcloud/db:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=Emphases5-Character3-Pranker3-Cornmeal8
        networks:
            - nextcloud-net
        image: postgres
        restart: always

    nextcloud:
        container_name: nextcloud
        ports:
            - 8080:80
        volumes:
            - /home/raspi/nextcloud/nextcloud:/var/www/html
        networks:
            - nextcloud-net
        image: nextcloud
        restart: always

networks:
    nextcloud-net:
        name: nextcloud-net
